spring:
  application:
    name: jchatmind
  datasource:
    url: jdbc:postgresql://localhost:5433/jchatmind
    username: postgres
    password: your_db_password
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: your_mail_username
    password: your_mail_password
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  ai:
    mcp:
      client:
        enabled: true
        connections: {}   # 在 application-local.yaml 中配置具体 MCP Server 连接
    deepseek:
      api-key: your_deepseek_api_key
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
    zhipuai:
      api-key: your_zhipuai_api_key
      base-url: https://open.bigmodel.cn/api/paas
      chat:
        options:
          model: glm-4.6
mybatis:
  type-aliases-package: com.kama.jchatmind.model.entity
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.kama.jchatmind.typehandler

document:
  storage:
    base-path: ./data/documents

weather:
  qweather:
    api-key: your_qweather_api_key
    api-host: your_qweather_api_host
    api-token: your_qweather_jwt_token
